const ADD_TASK = 'ADD_TASK';
const EDIT_TASK = 'EDIT_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const TOGGLE_TASKS = 'TOGLE_TASKS';
const ENABLE_FILTER = 'ENABLE_FILTER';
const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export {
  ADD_TASK,
  EDIT_TASK,
  UPDATE_TASK,
  DELETE_TASK,
  TOGGLE_TASKS,
  ENABLE_FILTER,
  CLEAR_COMPLETED
};
